src/controllers/VariableController.ts, src/index.ts, src/tests/controllers/VariableController.test.ts, types/VariableTypes.ts
This PR adjusts interface used for moving position of a list of variables
-   [WRS-506](https://support.chili-publish.com/projects/WRS/issues/WRS-506)
=> [Fix] Adjust interface used for moving position of a list of variables

src/controllers/DocumentController.ts
This PR fixes download document issue by removing the JSON.parse operation because no need to parse returned object anymore.
-   [WRS-544](https://support.chili-publish.com/projects/WRS/issues/WRS-544)
=> [Fix] Fix download document issue

.github/CODEOWNERS
This PR shows that there is a need for a CODE_OWNERS file with all developers in it for editor-sdk repo from the frontend team.
This will allow us to fetch reviews from everyone.
-   [WRS-597](https://support.chili-publish.com/projects/WRS/issues/WRS-597)
=> [Feature] CODEOWNER file for editor-sdk 

src/controllers/DebugController.ts, src/tests/__mocks__/FrameProperties.ts, src/tests/controllers/DebugController.test.ts
This PR updates the names of debug controller methods for fixing an wrong naming error.
=> [Fix] Debug controller method names

src/controllers/SubscriberController.ts, src/index.ts, src/interactions/connector.ts, src/tests/__mocks__/config.ts, src/tests/controllers/SubscriberContoller.test.ts, src/tests/interactions/connector.test.tsx, types/CommonTypes.ts
This PR adds a new editor method for listening selected layout's frames changes.
-   [WRS-725](https://support.chili-publish.com/projects/WRS/issues/WRS-725)
=> [Feature] Enable onSelectedLayoutFramesChanged method

src/controllers/SubscriberController.ts, types/CommonTypes.ts, webpack.config.js
This PR makes the methods in the SDK optional, so that integrators will not have errors if the don't include all the available methods.
-   [WRS-764](https://support.chili-publish.com/projects/WRS/issues/WRS-764)
=> [Feature] makes the methods in the SDK optional

types/TextStyleTypes.ts
This PR adds color property in TextProperties interface
-   [WRS-822](https://support.chili-publish.com/projects/WRS/issues/WRS-822)
=> [Fix] Add missing color property in TextProperties interface

src/controllers/AnimationController.ts, src/tests/controllers/AnimationController.test.ts
This PR sends missing data to setFrameAnimation call
=> [Fix] Pass animation data to setFrameAnimation method

src/index.ts
This PR bumps the editor engine version to 0.0.7 which includes, amongst others, Media Connectors, Configuration Api and default empty documents.
=> [Feature] Bump Editor Engine version

package.json
This PR fixes a build issue when taking dependency on editor-sdk
=> [Fix] husky postinstall breaks workspace builds

types/TextStyleTypes.ts
This PR corrects text font family key used for update
-   [WRS-863](https://support.chili-publish.com/projects/WRS/issues/WRS-863)
=> [Fix] Correct text font family key used for update

types/FrameTypes.ts
This PR adds missing fitMode property to Frame interface
-   [WRS-850](https://support.chili-publish.com/projects/WRS/issues/WRS-850)
=> [Fix] Add missing fitMode property to Frame interface

src/controllers/MediaConnectorController.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/controllers/MediaConnectorController.test.ts
This PR adds the authentication methods
-   [EDT-549](https://support.chili-publish.com/browse/EDT-549)
I'm using `connectorX` and not `mediaConnectorX` as we are now streamlining the naming (we have a bigger ticket for it).
Not sure a sub controller is the best structure here but we want the `SDK.connector.authentication.setChiliToken(id, token)` type of path. [Confluence](https://chilipublishintranet.atlassian.net/wiki/spaces/dev/pages/4054319145/Media+Connectors#Alpha---Epic)
=> [Feature] Add authentication methods

src/controllers/ConnectorController.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/controllers/ConnectorController.test.ts, types/FontConnectorTypes.ts, types/MediaConnectorTypes.ts
This PR renames the register connector method and add `pageSize` to the connector page models
-   [EDT-620](https://support.chili-publish.com/browse/EDT-620)
Can be tested against https://agreeable-mud-052c24203.azurestaticapps.net/?editor=EDT-620 and should be merged in sync with flutter.
=> [Fix] Naming and connector page models

src/controllers/SubscriberController.ts, src/index.ts, src/interactions/connector.ts, src/tests/__mocks__/config.ts, src/tests/controllers/SubscriberContoller.test.ts, src/tests/interactions/connector.test.tsx, types/CommonTypes.ts, types/LayoutTypes.ts
This PR adds `onSelectedLayoutIdChanged` and `onLayoutsChanged` listeners to SubscriberController.
-   [EDT-338](https://support.chili-publish.com/browse/EDT-338)
=> [Feature] Add `onSelectedLayoutIdChanged` and `onLayoutsChanged`

src/controllers/FrameController.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/controllers/FrameController.test.ts, types/FrameTypes.ts
This PR adds `reorderFrames` and `setFrameZIndex` methods to `FrameController`.
-   [EDT-628](https://support.chili-publish.com/browse/EDT-628)
=> [Feature] Add `reorderFrames` and `setFrameZIndex`  to `FrameController`

src/utils/enums.ts
This PR adds 'png' to the DownloadFormats enum.
-   [WRS-891](https://support.chili-publish.com/projects/WRS/issues/WRS-891)
=> [Fix] Add png to DownloadFormats enum

src/utils/enums.ts
My ticket referenced 'JPEG' fileformat, but the correct format should be 'JPG'.
-   [WRS-901](https://support.chili-publish.com/browse/WRS-901)
=> [Fix] Use correct file format

src/controllers/ConnectorController.ts, src/index.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/controllers/ConnectorController.test.ts, types/ConnectorTypes.ts
+ fix exports of Connector typings
This PR fixes some issues we had during development of integration examples. We enabled public API's for the setMapping feature and exposed all Connector Types from the SDK project.
=> Add Connector SetMapping / SetOptions

types/VariableTypes.ts
This PR adds `src` to the `Variable` type. It is based of the FrameImage typing.
-   [WRS-908](https://support.chili-publish.com/browse/WRS-908)
=> [Fix] Add Image Variable types

src/controllers/VariableController.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/controllers/VariableController.test.ts, types/VariableTypes.ts
This PR adds `setVariableSource` and `removeVariableSource` SDK methods on `VariableController`. 
-   [EDT-688](https://support.chili-publish.com/browse/EDT-688)
=> [Feature] Add `setVariableSource` and `removeVariableSource` SDK methods

src/index.ts
This PR adds missing exports for the types
-   [WRS-908](https://support.chili-publish.com/browse/WRS-908)
=> [Fix] Add missing exports to the SDK

src/tests/controllers/SubscriberContoller.test.ts, types/LayoutTypes.ts
This PR adds the layout type to `LayoutListItemType` for the list changed stream to in scope of the `stateChanged` refactoring.
- [EDT-747](https://support.chili-publish.com/browse/EDT-747)
- [WRS-883](https://support.chili-publish.com/browse/WRS-883)
=> [Fix] Add layoutType for listChanged stream

src/index.ts, types/FrameTypes.ts
This PR add missing exports for new enum.
=> [Fix] Add missing exports

src/controllers/FontController.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/controllers/FontController.test.ts
This PR adds `getDefaultFont`
-   [EDT-739](https://support.chili-publish.com/browse/EDT-739)
=> [Feature] Add default font

src/controllers/FontConnectorController.ts, src/controllers/MediaConnectorController.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/controllers/FontConnectorController.test.ts, src/tests/controllers/MediaConnectorController.test.ts
This PR adds support for fetching a specific asset from a given connector by id. 
-   [EDT-745](https://support.chili-publish.com/browse/EDT-745)
=> [Feature] Add `detail` method to Connectors

src/controllers/ExperimentController.ts, src/controllers/FrameController.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/controllers/ExperimentController.test.ts, src/tests/controllers/FrameController.test.ts, types/DocumentTypes.ts, types/FrameTypes.ts
This PR adds private method `updateImageSource` to FrameController to be able to set or reset the image source for the ImageFrame using the a single method exposed via Editor API
-   [EDT-693](https://support.chili-publish.com/browse/EDT-693)
=> [Feature] Add `setImageSource` to `FrameController`

src/controllers/ConnectorController.ts, src/controllers/SubscriberController.ts, src/index.ts, src/interactions/connector.ts, src/tests/__mocks__/config.ts, src/tests/controllers/SubscriberContoller.test.ts, src/tests/interactions/connector.test.tsx, types/CommonTypes.ts, types/ConnectorTypes.ts
This PR splits the connector states into events and states. 
-   [EDT-666](https://support.chili-publish.com/projects/EDT/issues/EDT-666)
=> [Fix] Clean up connector events and states

src/controllers/ExperimentController.ts, src/controllers/FrameController.ts, src/controllers/VariableController.ts, src/index.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/__mocks__/MockImageFrameSource.ts, src/tests/controllers/VariableController.test.ts, types/FrameTypes.ts, types/VariableTypes.ts
This PR converts `Variable` into multiple types `ImageVariable`, `GroupVariable`, `ShortTextVariable`, ...
This PR also corrects some other type names to better reflect what they mean. 
-   [EDT-611](https://support.chili-publish.com/browse/EDT-611)
=> [Feature] Convert Variable into union type

src/controllers/PageController.ts, src/controllers/SubscriberController.ts, src/index.ts, src/interactions/connector.ts, src/tests/__mocks__/MockEditorAPI.ts, src/tests/__mocks__/config.ts, src/tests/controllers/PageController.test.ts, src/tests/controllers/SubscriberContoller.test.ts, src/tests/interactions/connector.test.tsx, types/CommonTypes.ts, types/PageTypes.ts
This PR adds `setPageWidth`, `setPageHeight` and `onPageSizeChanged` SDK methods. This allows to update the page size while the document is of type `project`. If the document is a `template` these functions and listeners will do nothing. 
-   [EDT-814](https://support.chili-publish.com/projects/EDT/issues/EDT-814)
=> [EDT-814] Add Page Width, Height and OnPageSizeChanged

src/controllers/TextStyleController.ts, src/tests/controllers/TextStyleController.test.ts, types/CommonTypes.ts, types/TextStyleTypes.ts
This PR exposes the new `getSelectedTextStyle` method.
-   [EDT-856](https://support.chili-publish.com/browse/EDT-856)
=> [Feature] New getSelectedTextStyle method

src/controllers/FrameController.ts, src/controllers/ShapeController.ts, src/controllers/SubscriberController.ts, src/index.ts, src/interactions/connector.ts, src/tests/controllers/FrameController.test.ts, src/tests/controllers/ShapeController.test.ts, src/tests/controllers/SubscriberContoller.test.ts, src/types/CommonTypes.ts, src/types/DocumentTypes.ts, src/types/FrameTypes.ts, src/types/ShapeTypes.ts
This PR:
- added new methods to set corner radii for shapes
- added new types related to corner radii
- added new subscriber method to listen corner radii changes
- shape related methods moved from `FrameController` to the new `ShapeController`, BUT the FrameController ones remain functional
-   [EDT-711](https://support.chili-publish.com/browse/EDT-711)
=> [Feature] [EDT-711] Add CornerRadius methods for shapes

src/types/FrameTypes.ts, types/Actions.d.ts
This PR 
- renames the connector type from `assetProvider` to `connector` on Frame Types. 
- renames the connector type from `mediaConnector` to `connector` in Action Types.
=> [Fix] Update connector type

src/controllers/SubscriberController.ts, src/tests/controllers/SubscriberContoller.test.ts, src/types/CommonTypes.ts
This PR adds a subscription to track entering / exiting the crop mode by exposing `frameId?`
-   [EDT-970](https://support.chili-publish.com/browse/EDT-970)
=> [EDT-970] enter / exit crop mode notifications

src/controllers/ActionController.ts, src/tests/controllers/ActionController.test.ts
This PR adds `getActions`, `getActionById`, `renameAction` and `duplicateAction` SDK methods.
-   [EDT-723](https://support.chili-publish.com/browse/EDT-723)
=> Add remaining SDK methods for Actions

types/Actions.d.ts
This PR makes Action methods show up correctly as methods instead of properties.
=> [Fix] make methods show up as `method` in Action typings

types/Actions.d.ts
This PR add `Studio.layouts.all()` and adds `width`, `height` properties to the `Layout` model.
=> [Feature] Extend action models with layout list and size

src/sdk.ts
This PR fixes the naming of engine to info for consistency
=> [Fix] rename engine to info to be consistent

src/controllers/ConnectorController.ts, src/tests/controllers/ConnectorController.test.ts
Engine ticket: https://chilipublishintranet.atlassian.net/browse/EDT-1148
Can be tested against https://studio.chiligrafx-dev.com/?workspace=latest&engine=484&engineCommitSha=e6079e3ebfc15f0bfc18e33eeebee6058d778923
- `SDK.connector.getById` is now returning a `ConnectorInstance` (to align with `getAllByType`). It was originally returning a `ConnectorState` object and was confusing.
- `SDK.connector.getState` is the new name for the old `getById`, it returns a `ConnectorState`.
=> [Feature] [EDT-1148] Connector & State getter refactor

packages/sdk/src/controllers/ActionController.ts, packages/sdk/src/tests/controllers/ActionController.test.ts
https://chilipublishintranet.atlassian.net/browse/EDT-1156
https://chilipublishintranet.atlassian.net/browse/WRS-1342
---
A new `ActionController.setTypeError(id: string, hasTypeErrors: boolean)` has been added.
This is a way for the workspace to keep the state of the type errors (driven by WRS/monaco) after a new document load.
The error can be read from the usual action/document getters & most probably via the `actionsChanged` stream.
=> [Fix] Add setTypeError method for actions

packages/sdk/src/tests/controllers/ConnectorController.test.ts, packages/sdk/src/types/CommonTypes.ts, packages/sdk/src/utils/EditorResponseData.ts
This PR is a POC on throwing errors.
The SDK will now throw errors when something goes wrong instead of success status false.
=> [Feature] Error handling by throw

packages/sdk/src/controllers/FontController.ts, packages/sdk/src/tests/controllers/FontController.test.ts
This PR adds a method which returns a default `DocumentFontFamily`
-   [EDT-1177](https://chilipublishintranet.atlassian.net/browse/EDT-1177)
[WRS-1177]: https://chilipublishintranet.atlassian.net/browse/WRS-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDT-1177]: https://chilipublishintranet.atlassian.net/browse/EDT-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] getDefaultFontFamily() method added

packages/sdk/src/controllers/MediaConnectorController.ts, packages/sdk/src/types/ConnectorTypes.ts, packages/sdk/src/types/FontConnectorTypes.ts, packages/sdk/src/types/MediaConnectorTypes.ts, types/Connector.Shared.d.ts, types/FontConnector.d.ts, types/MediaConnector.d.ts
This PR adds `width` & `height` to the model returned by the connector `detail` method. `MediaDetail` model is now diverging from `Media` (query method).
https://chilipublishintranet.atlassian.net/browse/EDT-1054
=> [Feature] Add width & height to media detail model

packages/sdk/src/index.ts
This PR adds missing export of Layout type
-   [WRS-1377](https://support.chili-publish.com/projects/WRS/issues/WRS-1377)
[WRS-1377]: https://chilipublishintranet.atlassian.net/browse/WRS-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] Export Layout type

packages/sdk/src/index.ts
This PR exports `SelectedTextStyle` type from index.ts
=> [Fix] export `SelectedTextStyle` type from index.ts

packages/sdk/src/controllers/ActionController.ts, packages/sdk/src/tests/controllers/ActionController.test.ts, packages/sdk/src/types/ActionTypes.ts
This PR adds `SDK.action.updateAction('id', deltaUpdateModel);`
This allows you to update one or more of the following properties at the same time:
- name
- script
- triggers
- hasTypeError
-   [EDT-1139](https://chilipublishintranet.atlassian.net/browse/EDT-1139)
[EDT-1139]: https://chilipublishintranet.atlassian.net/browse/EDT-1139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] Add Action delta update method

packages/sdk/src/tests/controllers/CharacterStyleController.test.ts, packages/sdk/src/tests/controllers/ParagraphStyleController.test.ts, packages/sdk/src/types/CharacterStyleTypes.ts, packages/sdk/src/types/ParagraphStyleTypes.ts, packages/sdk/src/types/TextStyleTypes.ts
This PR
-   [EDT-533] - Implement letter spacing (tracking)
[EDT-533]: https://chilipublishintranet.atlassian.net/browse/EDT-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [EDT-533] - Implement letter spacing (tracking)

packages/sdk/src/controllers/SubscriberController.ts, packages/sdk/src/interactions/connector.ts, packages/sdk/src/sdk.ts, packages/sdk/src/tests/__mocks__/config.ts, packages/sdk/src/tests/controllers/SubscriberContoller.test.ts, packages/sdk/src/types/CommonTypes.ts, packages/sdk/src/types/ConnectorTypes.ts
This PR is a SPIKE!
Allows for blocking https requests on engine-side until a new token is returned by the `onAuthExpired` listener.
[EDT-1231](https://chilipublishintranet.atlassian.net/browse/EDT-1231)
[EDT-1231]: https://chilipublishintranet.atlassian.net/browse/EDT-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] Add onAuthExpired listener

packages/sdk/src/tests/controllers/VariableController.test.ts, packages/sdk/src/types/VariableTypes.ts
This PR adds the resolved `mediaId` to the `ImageVariable` model. This will enable you to retrieve the media Id when only the asset name was set as the image variable value.
=> [EDT-1251] Add resolved property to image variable model

packages/sdk/src/types/TextStyleTypes.ts
This PR adds 'trackingRight' property to SelectedTextStyle
-   [WRS-798](https://support.chili-publish.com/projects/WRS/issues/WRS-798)
[WRS-798]: https://chilipublishintranet.atlassian.net/browse/WRS-798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] Add 'trackingRight' property to SelectedTextStyle

packages/sdk/src/controllers/ToolController.ts, packages/sdk/src/tests/controllers/ToolController.test.ts
This PR returns the `EditorResponse` from the `SDK.tool.setZoom()` call.
=> [Fix] Return editor response on `setZoom` call

README.md
This PR adds a studio-ui link to the README and fixes the NPM badges
=> [Fix] Add Studio UI link to SDK and fix NPM badge

packages/sdk/src/index.ts
This PR exports LayoutIntent as enum instead of type.
-   [WRS-1560](https://support.chili-publish.com/projects/WRS/issues/WRS-1560)
[WRS-1560]: https://chilipublishintranet.atlassian.net/browse/WRS-1560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] Export LayoutIntent as enum instead of type

packages/sdk/src/tests/controllers/ConnectorController.test.ts, packages/sdk/src/types/ConnectorTypes.ts
This PR adds the `direction` property to `ConnectorMapping` 
-   [EDT-1272](https://chilipublishintranet.atlassian.net/browse/EDT-1272)
[EDT-1272]: https://chilipublishintranet.atlassian.net/browse/EDT-1272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] Add direction to connector mapping

packages/sdk/src/controllers/LayoutController.ts, packages/sdk/src/tests/controllers/LayoutController.test.ts
This PR aligns with our usual naming.
=> [Fix] Rename setLayoutIntent to setIntent

packages/sdk/src/index.ts, packages/sdk/src/utils/enums.ts
This PR extends LayoutPropertyNames with bleed property names
-   [WRS-1579](https://support.chili-publish.com/projects/WRS/issues/WRS-1579)
[WRS-1579]: https://chilipublishintranet.atlassian.net/browse/WRS-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] Extend LayoutPropertyNames with bleed property names

packages/sdk/src/controllers/SubscriberController.ts, packages/sdk/src/controllers/VariableController.ts, packages/sdk/src/index.ts, packages/sdk/src/tests/controllers/SubscriberContoller.test.ts, packages/sdk/src/tests/controllers/VariableController.test.ts, packages/sdk/src/types/VariableTypes.ts
Part 1 of 2. 
In this PR a backwards compatibility layer is created to keep the contracts working with the new engine feature.
-   [EDT-1338](https://chilipublishintranet.atlassian.net/browse/EDT-1338)
[EDT-1338]: https://chilipublishintranet.atlassian.net/browse/EDT-1338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] [EDT-1338] Add display value for list items (backwards compatibility layer)

packages/sdk/src/controllers/ClipboardController.ts, packages/sdk/src/controllers/FrameController.ts, packages/sdk/src/controllers/LayoutController.ts, packages/sdk/src/tests/controllers/ClipboardController.test.ts, packages/sdk/src/tests/controllers/LayoutController.test.ts, packages/sdk/src/types/ClipboardTypes.ts, packages/sdk/src/types/LayoutTypes.ts
This PR
-   [EDT-1424](https://chilipublishintranet.atlassian.net/browse/EDT-1424)
[EDT-1424]: https://chilipublishintranet.atlassian.net/browse/EDT-1424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Add simple way to enable/disable layout fill

packages/sdk/src/utils/enums.ts
This PR gets pdf out of experimental.
This is a breaking experimental change
=> [Fix] PDF output out of experimental

.github/CODEOWNERS
This PR fixes the codeowner assignment
=> [Fix] CODEOWNERS correctness(l) 🔒

packages/sdk/src/controllers/BarcodeController.ts, packages/sdk/src/tests/controllers/BarcodeController.test.ts
This PR allows barcode frame sources to receive null as a source.
-   [WRS-1644](https://support.chili-publish.com/projects/WRS/issues/WRS-1644)
[WRS-1644]: https://chilipublishintranet.atlassian.net/browse/WRS-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] Allow barcode frame sources to receive null as a source

packages/sdk/src/controllers/CharacterStyleController.ts, packages/sdk/src/controllers/ParagraphStyleController.ts, packages/sdk/src/tests/controllers/CharacterStyleController.test.ts
This PR adds the missing `move` method on `CharacterStyleController`.
=> [Feature] [EDT-1465] Allow reordering character styles

packages/sdk/src/sdk.ts
This PR comments out the `next.subscriber.onVariableListChanged` as it overrides the variables list which currently breaks the studio workspace and studio ui
=> [Fix] Fix list variables 

packages/actions/scripts/prepare-release.mjs, packages/actions/src/ActionHelpers.ts, packages/actions/types/Actions.d.ts
This PR adds `NumberVariable` support to `Actions` and helper methods.
-   [EDT-1482](https://chilipublishintranet.atlassian.net/browse/EDT-1482)
[EDT-1482]: https://chilipublishintranet.atlassian.net/browse/EDT-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] [EDT-1482] Add `NumberVariable` to Actions

packages/sdk/src/README.md, packages/sdk/src/controllers/VariableController.ts, packages/sdk/src/index.ts, packages/sdk/src/tests/controllers/VariableController.test.ts, packages/sdk/src/types/VariableTypes.ts
This PR
- [X I have read the [contribution and PR guidelines](/chili-publish/studio-sdk/blob/main/CONTRIBUTING.md)
-   [EDT-1500](https://chilipublishintranet.atlassian.net/browse/EDT-1500)
[EDT-1500]: https://chilipublishintranet.atlassian.net/browse/EDT-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [EDT-1500] Add date variable definition

packages/connectors/src/Connector.Shared.ts, packages/sdk/src/types/CommonTypes.ts, packages/sdk/src/types/ConnectorTypes.ts
This PR updates the type of the context values to support `boolean` values.
-   [EDT-1315](https://chilipublishintranet.atlassian.net/browse/EDT-1315)
[EDT-1315]: https://chilipublishintranet.atlassian.net/browse/EDT-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] Update connector `context` value types

packages/sdk/src/controllers/ConnectorController.ts, packages/sdk/src/tests/controllers/ConnectorController.test.ts, packages/sdk/src/types/ConnectorTypes.ts
This PR adds type safety when working with ConnectorMapping. It also adds possibility to retrieve specified mapping for provided direction (with again type safety around `value` field)
=> [FEATURE] Strict typings on connectors mapping

packages/sdk/src/README.md, packages/sdk/src/README_HTML.md, packages/sdk/src/controllers/SubscriberController.ts
Documentation on eventual consistency.
=> [Fix] Note on eventual consistency

packages/sdk/src/interactions/connector.ts, packages/sdk/src/tests/interactions/connector.test.tsx
=> [Fix][EDT-1579] Chrome Loading Bug

.github/actions/get-gh-app-installation-access-token/action.yml, .github/actions/get-gh-app-installation-access-token/get-gh-app-installation-access-token.ps1, .github/actions/get-gh-app-jwt/action.yml, .github/actions/get-gh-app-jwt/get-gh-app-jwt.ps1, .github/workflows/trigger-automated-tests.yml
This PR adds the posibility to run automated tests for the SDK methods using a newly added label called `Ready for QA` 
-   [QA-680](https://support.chili-publish.com/projects/QA/issues/QA-680)
[QA-680]: https://chilipublishintranet.atlassian.net/browse/QA-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] Add workflow to run automated tests

packages/sdk/src/controllers/VariableController.ts, packages/sdk/src/index.ts, packages/sdk/src/next/types/VariableTypes.ts, packages/sdk/src/tests/controllers/VariableController.test.ts, packages/sdk/src/types/VariableTypes.ts
This PR
-   [EDT-1592](https://chilipublishintranet.atlassian.net/browse/EDT-1592)
[EDT-1592]: https://chilipublishintranet.atlassian.net/browse/EDT-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE][EDT-1592] Add interfaces for prefixes and suffixes

packages/sdk/tsconfig.json
This PR adds the NextInitiator and controllers to the docs
-   [WRS-1983](https://support.chili-publish.com/projects/WRS/issues/WRS-1983)
=> [Fix] NextInitiator and Controllers not in docs

packages/sdk/src/index.ts, packages/sdk/src/tests/utils/editorResponseData.test.ts, packages/sdk/src/utils/EditorResponseData.ts
This PR will throw a `ConnectorHttpError` instead of a generic `Error` whenever an http request from the connector fails. The http status code will be reported into the new error type.
https://github.com/chili-publish/studio-engine/pull/1476
🔓 Unblocks https://chilipublishintranet.atlassian.net/browse/WRS-2002
=> [Fix] Throw a ConnectorHttpError when the engine error code matches

packages/sdk/src/index.ts
This fixes the export for ColorUsageType, and other `enum` or `class` types that are exported as TypeAlias.
`
Example where it goes wrong:
```ts
(async () => {
// Fetch all frames to find the ID of the frame named 'InventoryBarcode'
const framesResponse = await window.SDK.frame.getAll();
const frames = framesResponse.parsedData;
// Find the frame with name 'InventoryBarcode', case insensitive
const inventoryBarcodeFrame = frames.find(frame => frame.name.toLowerCase() === 'inventorybarcode');
if (!inventoryBarcodeFrame) {
throw new Error("Frame 'InventoryBarcode' not found");
}
const frameId = inventoryBarcodeFrame.id;
// Define the custom hex color
const backgroundColor: ColorUsage = {
color: {
value: '#FF5733',
type: ColorType.hex
},
type: ColorUsageType.local
};
// Set the background …
```
=> ColorUsageType is not exported as usable enum

packages/sdk/src/controllers/LayoutController.ts, packages/sdk/src/tests/controllers/LayoutController.test.ts, packages/sdk/src/types/LayoutTypes.ts
This PR adds a new `availableForUser` property on the layout models and a new SDK method `setAvailableForUser`.
https://chilipublishintranet.atlassian.net/browse/EDT-1756
https://chilipublishintranet.atlassian.net/browse/WRS-2280
----
Engine PR: https://github.com/chili-publish/studio-engine/pull/1648
=> [Feature] [EDT-1756] Add available for user property to layouts

packages/sdk/src/types/PageTypes.ts
This PR adds `maxWaitTimeMs` to `SnapshotSettings`.
-   [EDT-1817](https://chilipublishintranet.atlassian.net/browse/EDT-1817)
[EDT-1817]: https://chilipublishintranet.atlassian.net/browse/EDT-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] [EDT-1817] [Snapshot] Define maximum time to wait for assets to be loaded

packages/sdk/src/controllers/SubscriberController.ts, packages/sdk/src/interactions/Connector.ts, packages/sdk/src/sdk.ts, packages/sdk/src/tests/__mocks__/Config.ts, packages/sdk/src/tests/controllers/SubscriberContoller.test.ts, packages/sdk/src/types/CommonTypes.ts, packages/sdk/src/utils/ConfigHelper.ts
This PR adds a new `onAllFramesLayoutChanged` stream that is a deviation from already existing `onSelectedFramesLayoutChanged`.
Alternative name: `onFramesLayoutChanged`
https://chilipublishintranet.atlassian.net/browse/EDT-1875
https://chilipublishintranet.atlassian.net/browse/WRS-1284
=> [Fix] Add onFramesLayoutChanged

packages/sdk/src/controllers/FrameController.ts, packages/sdk/src/tests/controllers/FrameController.test.ts
This PR adds a new `resetFrameVisibility` method
To be discussed: `resetFrameIsVisible`?
https://chilipublishintranet.atlassian.net/browse/EDT-1874
https://chilipublishintranet.atlassian.net/browse/WRS-1284
=> [Fix] Add frame visibility reset

packages/sdk/src/controllers/FrameController.ts, packages/sdk/src/tests/controllers/FrameController.test.ts, packages/sdk/src/types/FrameTypes.ts
This PR adds a new `getConfiguration` method to the frame controller to get configurations given certain behaviors of a frame.
https://chilipublishintranet.atlassian.net/browse/EDT-1876
=> [Feature] Provide valid configurations and targets for anchoring to sdk

packages/sdk/src/controllers/VariableController.ts, packages/sdk/src/next/controllers/VariableController.ts, packages/sdk/src/next/tests/controllers/VariableController.test.ts, packages/sdk/src/tests/controllers/VariableController.test.ts, packages/sdk/src/types/VariableTypes.ts
This PR adds `setAllowImageQuery` & `setAllowImageUpload` to the variable controller.
https://chilipublishintranet.atlassian.net/browse/WRS-2439
https://chilipublishintranet.atlassian.net/browse/EDT-1951
=> [Feature] Add allowUpload & allowQuery to image variable

packages/sdk/src/controllers/FrameController.ts, packages/sdk/src/tests/controllers/FrameController.test.ts
This PR adds resetAllAssetCropOverrides method
-   [EDT-1955](https://chilipublishintranet.atlassian.net/browse/EDT-1955)
[EDT-1955]: https://chilipublishintranet.atlassian.net/browse/EDT-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature][EDT-1955]  resetAllAssetCropOverrides

packages/sdk/src/controllers/PageController.ts, packages/sdk/src/controllers/SubscriberController.ts, packages/sdk/src/interactions/Connector.ts, packages/sdk/src/tests/controllers/SubscriberContoller.test.ts, packages/sdk/src/types/CommonTypes.ts
This PR
- Fix actual param we're sending for `onPageSnapshotInvalidated` to be aligned with API (eventually it's string, was a number)
- Fix the API type for `page.add` and `page.remove` methods of PageController
- Deprecate the `onPageSelectionChanged` event as not implemented from the Engine
-   [WRS-2521](https://support.chili-publish.com/projects/WRS/issues/WRS-2521)
[WRS-2521]: https://chilipublishintranet.atlassian.net/browse/WRS-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2521] Fix return type and actual param value for certain page controller methods and events

packages/sdk/src/controllers/BrandKitController.ts, packages/sdk/src/controllers/MediaConnectorController.ts, packages/sdk/src/tests/controllers/MediaConnectorController.test.ts, packages/sdk/src/utils/EditorResponseData.ts
This PR throws an exception on media connector download call in case of error from engine
-   [WRS-2575](https://support.chili-publish.com/projects/WRS/issues/WRS-2575)
[WRS-2575]: https://chilipublishintranet.atlassian.net/browse/WRS-2575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2575] Throw exception on media connector download call in case of error from engine
