chili-publish/studio-sdk

- .github/workflows/publish-release-npm.yml
- .npmrc
- package.json
This PR automates the NPM builds to public NPM
-   [WRS-467](https://support.chili-publish.com/projects/WRS/issues/WRS-467)
> [Feature] Automate NPM builds

- .github/workflows/publish-release-npm.yml
This PR adds the registry url to the publish action
> [Fix] NPM Automate add registry url

- .github/workflows/publish-release-npm.yml
- README.md
This PR fixes the Azure upload path issue on release
> [Fix] Azure upload path fix on release

- src/controllers/AnimationController.ts
- src/controllers/FrameController.ts
- src/controllers/LayoutController.ts
- src/controllers/PageController.ts
- src/controllers/SubscriberController.ts
- src/controllers/ToolController.ts
- src/controllers/VariableController.ts
- src/index.ts
- src/tests/__mocks__/FrameProperties.ts
- src/tests/controllers/AnimationController.test.ts
- src/tests/controllers/FrameController.test.ts
- src/tests/controllers/LayoutController.test.ts
- src/tests/controllers/PageController.test.ts
- src/tests/controllers/SubscriberContoller.test.ts
- src/tests/controllers/ToolController.test.ts
- src/tests/controllers/VariableController.test.ts
- src/utils/enums.ts
- types/CommonTypes.ts
- types/FrameTypes.ts
- types/LayoutTypes.ts
- types/PageTypes.ts
This PR implements new exposed Flutter getter methods
-   [WRS-475](https://support.chili-publish.com/projects/WRS/issues/WRS-475)
> [Feature] Implement new exposed Flutter getter methods

- src/controllers/ToolController.ts
- src/tests/controllers/ToolController.test.ts
This PR fixes the enum name that changed at the latest develop
> [Fix] Update enum names for fixing test cases

- src/controllers/VariableController.ts
- src/index.ts
- src/tests/__mocks__/FrameProperties.ts
- src/tests/controllers/VariableController.test.ts
- types/VariableTypes.ts
This PR adds a new method called 'moveVariables' used for changing multiple variables positions
-   [WRS-506](https://support.chili-publish.com/projects/WRS/issues/WRS-506)
> [Feature] Expose new method moveVariables

- src/controllers/VariableController.ts
- src/tests/controllers/VariableController.test.ts
This PR adjusts moveVariables api
-   [WRS-506](https://support.chili-publish.com/projects/WRS/issues/WRS-506)
> [Fix] Adjust moveVariables api

- src/controllers/DebugController.ts
- src/index.ts
- src/tests/__mocks__/FrameProperties.ts
- src/tests/controllers/DebugController.test.ts
This PR implements debug controller.
-   [WRS-601](https://support.chili-publish.com/projects/WRS/issues/WRS-601)
> [Feature] Implement debug controller

- src/controllers/SubscriberController.ts
- src/controllers/UndoController.ts
- src/controllers/UndoManagerController.ts
- src/index.ts
- src/interactions/connector.ts
- src/tests/__mocks__/FrameProperties.ts
- src/tests/__mocks__/config.ts
- src/tests/controllers/SubscriberContoller.test.ts
- src/tests/controllers/UndoController.test.ts
- src/tests/interactions/connector.test.tsx
- types/CommonTypes.ts
- types/DocumentTypes.ts
This PR adds undo/redo controller methods
-   [WRS-630](https://support.chili-publish.com/projects/WRS/issues/WRS-630)
> [Feature] Implement undo controller

- src/controllers/VariableController.ts
- src/tests/__mocks__/FrameProperties.ts
- src/tests/controllers/VariableController.test.ts
This PR updates removeVariables method
-   [WRS-654](https://support.chili-publish.com/projects/WRS/issues/WRS-654)
> [Feature] Update removeVariables method

- types/AnimationTypes.ts
This PR adds new keys to BasicAnimationsEmphasisType
-   [WRS-350](https://support.chili-publish.com/projects/WRS/issues/WRS-350)
> [Fix] Add missing style keys

- docs/classes/controllers_AnimationController.AnimationController.html
- docs/classes/controllers_DocumentController.DocumentController.html
- docs/classes/controllers_FrameController.FrameController.html
- docs/classes/controllers_LayoutController.LayoutController.html
- docs/classes/controllers_ToolController.ToolController.html
- docs/classes/controllers_UtilsController.UtilsController.html
- docs/classes/controllers_VariableController.VariableController.html
- docs/classes/index.SDK.html
- docs/enums/index.BasicAnimationsEmphasisStyles.html
- docs/enums/index.BlendMode.html
- docs/enums/index.DownloadFormats.html
- docs/enums/index.EaseTypes.html
- docs/enums/index.FlowDirection.html
- docs/enums/index.FrameProperyNames.html
- docs/enums/index.FrameTypeEnum.html
- docs/enums/index.LayoutProperyNames.html
- docs/enums/index.LayoutType.html
- docs/enums/index.ShakeDirections.html
- docs/enums/index.SlideDirections.html
- docs/enums/index.TextDirection.html
- docs/enums/index.ToolType.html
- docs/enums/index.TweenTypes.html
- docs/enums/index.VariableType.html
- docs/enums/index.VerticalAlign.html
- docs/modules/index.html
This PR updates the documentation to the latest version
> [Feature] Update documentation

- src/controllers/FrameController.ts
- src/tests/__mocks__/FrameProperties.ts
- src/tests/controllers/FrameController.test.ts
This PR Adds the remove frame function to the SDK
-   [WRS-780](https://support.chili-publish.com/projects/WRS/issues/WRS-780)
> [Feature] Add remove frame function

- .github/workflows/publish-release-npm.yml
This PR adds the latest tag to the NPM release job
> [Fix] NPM Release tag latest

- types/TextStyleTypes.ts
This PR Adds color to text styles enum
-   [WRS-793](https://support.chili-publish.com/projects/WRS/issues/WRS-793)
> [Feature] Add color to text styles enum

- src/index.ts
- types/ParagraphStyleTypes.ts
This PR fixes color property in ParagraphStyle interface
-   [WRS-802](https://support.chili-publish.com/projects/WRS/issues/WRS-802)
> [Fix] Fix color property in ParagraphStyle interface

- src/controllers/AnimationController.ts
- src/controllers/ColorStyleController.ts
- src/controllers/DebugController.ts
- src/controllers/DocumentController.ts
- src/controllers/FrameController.ts
- src/controllers/LayoutController.ts
- src/controllers/PageController.ts
- src/controllers/ParagraphStyleController.ts
- src/controllers/SubscriberController.ts
- src/controllers/TextStyleController.ts
- src/controllers/ToolController.ts
- src/controllers/UndoManagerController.ts
- src/controllers/UtilsController.ts
- src/controllers/VariableController.ts
- src/tests/__mocks__/FrameProperties.ts
- src/tests/controllers/DocumentController.test.ts
- src/tests/controllers/UtilsController.test.ts
- src/utils/EditorResponseData.ts
- types/CharacterStyleTypes.ts
- types/ColorStyleTypes.ts
- types/CommonTypes.ts
- types/DebugTypes.ts
- types/DocumentTypes.ts
- types/LayoutTypes.ts
- types/ParagraphStyleTypes.ts
This PR uses typescript in order to type EditorResponse in a generic way
-   [WRS-807](https://support.chili-publish.com/projects/WRS/issues/WRS-807)
> [Feature] Type EditorResponse as generic

- .github/workflows/pr-build.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-package.yml
- .github/workflows/publish-release-npm.yml
- src/index.ts
- types/CommonTypes.ts
This PR updates pipelines to go to correct PRD and DEV environments as well as fixing the editor version in place
-   [WRS-800](https://support.chili-publish.com/projects/WRS/issues/WRS-800)
> [Feature] Update SDK to DEV and PRD pipelines and fixed editor

- src/controllers/MediaConnectorController.ts
- types/MediaConnectorTypes.ts
This PR fixes the download resolution enum
-   [WRS-865](https://support.chili-publish.com/projects/WRS/issues/WRS-865)
> [Fix] Download resolution enum

- src/controllers/MediaConnectorController.ts
- types/MediaConnectorTypes.ts
This PR fixes the media types with deprecation of old tyeps
-   [WRS-835](https://support.chili-publish.com/projects/WRS/issues/WRS-835)
> [Fix] Media types deprecation

- src/index.ts
This PR exports metadata type
-   [WRS-835](https://support.chili-publish.com/projects/WRS/issues/WRS-835)
> [Fix] Export MetaData type

- src/controllers/FrameController.ts
This PR adds the assignImageToFrame call
-   [WRS-835](https://support.chili-publish.com/projects/WRS/issues/WRS-835)
> [Feature] Add assign image to imageFrame

- types/CharacterStyleTypes.ts
- types/ParagraphStyleTypes.ts
- types/TextStyleTypes.ts
This PR adjusts naming of font information
-   [WRS-863](https://support.chili-publish.com/projects/WRS/issues/WRS-863)
> [Fix] Adjust naming of font information

- src/controllers/ConnectorController.ts
- src/controllers/FrameController.ts
- src/index.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/ConnectorController.test.ts
- types/ConnectorTypes.ts
- types/FrameTypes.ts
This PR Adds some missing SDK methods and rename the assignImageToFrame method
> [Feature] Prepare connector launch

- types/ConnectorTypes.ts
This PR adds string enum values for Connector enums
> [Fix] Add string enum values for Connector enums

- src/index.ts
> [Fix] bump editor engine to 0.11

- src/controllers/FrameController.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/FrameController.test.ts
- types/CommonTypes.ts
- types/TextStyleTypes.ts
This PR implements frame vertical alignment update
-   [WRS-794](https://support.chili-publish.com/projects/WRS/issues/WRS-794)
> [Feature] Implement frame vertical alignment update

- src/controllers/AnimationController.ts
- src/controllers/DocumentController.ts
- src/controllers/FrameController.ts
- src/controllers/LayoutController.ts
- src/controllers/PageController.ts
- src/index.ts
- src/tests/__mocks__/FrameProperties.ts
- src/tests/__mocks__/animations.ts
- src/tests/controllers/AnimationController.test.ts
- src/tests/controllers/DocumentController.test.ts
- src/tests/controllers/FrameController.test.ts
- src/tests/controllers/LayoutController.test.ts
- src/tests/controllers/PageController.test.ts
- src/tests/utils/getFetchUrls.test.ts
- src/utils/getFetchUrl.ts
- types/AnimationTypes.ts
- types/CommonTypes.ts
- types/DocumentTypes.ts
- types/FrameTypes.ts
- types/LayoutTypes.ts
- types/PageTypes.ts
> [Fix] WRS-829 Convert number to string for all ids

- src/README.md
- src/README_HTML.md
- tsconfig.json
> [Fix] Add new controllers to documentation

- src/tests/controllers/ParagraphStyleController.test.ts
- types/ColorStyleTypes.ts
- types/ParagraphStyleTypes.ts
This PR adds `isApplied`, `opacity` properties on `ColorUsage` and `ColorUsageUpdate`
-   [EDT-579](https://support.chili-publish.com/browse/EDT-579)
> [Feature] Add checkbox state for fill color of text

- types/FrameTypes.ts
This PR updates the Z-Index names to the correct ones. 
-   [EDT-628](https://support.chili-publish.com/browse/EDT-628)
> [Fix] Use new Z-Index names

- src/utils/enums.ts
This PR updates DownloadFormats enum.
-   [WRS-901](https://support.chili-publish.com/browse/WRS-901)
> [Fix] Update DownloadFormats enum

- src/controllers/LayoutController.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/LayoutController.test.ts
This PR exposes the getSnapshotApi function in the engine
-   [EDT-635](https://support.chili-publish.com/browse/EDT-635)
> [Feature] Add basic snapshot SDK function

- src/controllers/FrameController.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/FrameController.test.ts
This PR adds `setImageFromUrl` on `FrameController`. 
-   [EDT-661](https://support.chili-publish.com/browse/EDT-661)
> [Feature] Add `setImageFromUrl` on `FrameController`

- src/controllers/ConnectorController.ts
- src/controllers/FontController.ts
- src/controllers/LayoutController.ts
- src/index.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/ConnectorController.test.ts
- src/tests/controllers/SubscriberContoller.test.ts
This PR exports ZIndexMethod type
-   [WRS-920](https://support.chili-publish.com/projects/WRS/issues/WRS-920)
> [Feature] Export ZIndexMethod type

- src/controllers/ConnectorController.ts
This PR gives some clarification on the registration and authentication flow. A previous PR added some information which was misleading and trapped Alexandra.
- [EDT-631](https://support.chili-publish.com/browse/EDT-631)
> [Fix] Misleading doc on setHttpHeader

- types/FrameTypes.ts
This PR adds copyfitting properties to Frame interface
-   [WRS-915](https://support.chili-publish.com/projects/WRS/issues/WRS-915)
> [Feature] Add copyfitting properties to Frame interface

- src/controllers/FrameController.ts
- types/LayoutTypes.ts
- types/MediaConnectorTypes.ts
This PR fices some media connector types
> [Fix] Metadata correct types

- src/controllers/ConnectorController.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/ConnectorController.test.ts
- types/CommonTypes.ts
This PR adds frameType to SelectedLayoutFrame
-   [WRS-914](https://support.chili-publish.com/projects/WRS/issues/WRS-914)
> [Fix] Add frameType to SelectedLayoutFrame

- src/controllers/CharacterStyleController.ts
- src/index.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/CharacterStyleController.test.ts
This PR adds a new controller (CharacterStyleController) containing methods for creating and retrieving the character styles
-   [WRS-805](https://support.chili-publish.com/projects/WRS/issues/WRS-805)
> [Feature] Add CharacterStyle controller

- src/controllers/CharacterStyleController.ts
- src/index.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/CharacterStyleController.test.ts
- types/CharacterStyleTypes.ts
- types/TextStyleTypes.ts
This PR implements new method used for updating a character style
-   [WRS-803](https://support.chili-publish.com/projects/WRS/issues/WRS-803)
> [Feature] Implement character style update

- types/FontConnectorTypes.ts
- types/MediaConnectorTypes.ts
This PR adds the `extension` property to the `Media`/`Font` models.
-   [EDT-662](https://support.chili-publish.com/browse/EDT-662)
[Flutter PR](https://bitbucket.chili-publish.com/projects/EDITOR2/repos/editor/pull-requests/423/overview)
Can be tested against [this build](https://studio-dev.chiligrafx.com/bench.html?workspace=latest&engine=EDT-662).
> [Fix] added extension to connector assets models

- src/index.ts
- types/VariableTypes.ts
Did not exported typings required by ImagePicker Pull Request.
> [Fix] Add ImageVariable typings

- src/controllers/CharacterStyleController.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/CharacterStyleController.test.ts
This PR add new methods to remove, duplicate and rename a character style.
-   [WRS-944](https://support.chili-publish.com/projects/WRS/issues/WRS-944)
> [Feature] Add character style remove, duplicate and rename methods

- .github/workflows/pr-build.yml
- .github/workflows/publish-package.yml
- .github/workflows/publish-release-npm.yml
This PR fixes the upload of the build artifacts
> [Fix] Correct upload pipeline

- src/controllers/FrameController.ts
- src/index.ts
- src/tests/controllers/CharacterStyleController.test.ts
- src/tests/controllers/ParagraphStyleController.test.ts
- types/CharacterStyleTypes.ts
- types/ColorStyleTypes.ts
- types/DocumentTypes.ts
- types/ParagraphStyleTypes.ts
- types/TextStyleTypes.ts
This PR adds fillColorApplied property to CharacterStyle and ParagraphStyle
-   [WRS-849](https://support.chili-publish.com/projects/WRS/issues/WRS-849)
> [Feature] Add fillColorApplied to Character and Paragraph Style

- src/index.ts
- src/tests/controllers/SubscriberContoller.test.ts
- types/LayoutTypes.ts
This PR exports type needed on layoutsChanged event
-   [WRS-883](https://support.chili-publish.com/projects/WRS/issues/WRS-883)
> [Fix] Export type used on layoutsChanged event

- types/FrameTypes.ts
This PR updates the src property on frame type to correctly match the object shapes
-   [WRS-854](https://support.chili-publish.com/projects/WRS/issues/WRS-854)
> [FIX] Updated the src property on frames to correctly match the object shapes

- src/controllers/SubscriberController.ts
- src/tests/controllers/SubscriberContoller.test.ts
- types/CommonTypes.ts
This PR removes the document from the stateChanged stream
https://support.chili-publish.com/browse/EDT-636
Can be tested against https://studio-dev.chiligrafx.com/?workspace=latest&engine=39
> [EDT-636] remove doc from stateChanged

- src/controllers/ExperimentController.ts
- src/controllers/FrameController.ts
This PR adds sdk call for setting image from variable
-   [WRS-854](https://support.chili-publish.com/projects/WRS/issues/WRS-854)
> Added sdk call for setting image from variable

- src/tests/__mocks__/MockEditorAPI.ts
This PR adds the missing mock.
> [Fix] Add `assignImageVariable` mock.

- .github/workflows/publish-package.yml
This PR fixes the SDK thinking it has the wrong version
-   [EDT-583](https://support.chili-publish.com/projects/WRS/issues/EDT-583)
> [Fix] SDK needs to know correct version

- src/controllers/ConnectorController.ts
This PR fixed media connector loading 🙏
-   [EDT-806](https://support.chili-publish.com/browse/EDT-806)
-  `WaitForConnectorReady` is definitely a workaround & don't want to test it in scope of this ticket
- Will probably be replaced by an event or a different flow
You can test it against https://studio-dev.chiligrafx.com/?workspace=latest&engine=74
> [Fix] Wait for proper connector states

- src/index.ts
- src/tests/__mocks__/config.ts
- types/CommonTypes.ts
- types/ConfigurationTypes.ts
- types/DocumentTypes.ts
This PR adds project and template-specific document types.
-   [EDT-643](https://support.chili-publish.com/browse/EDT-643)
> [Feature] Add Project/Template specific properties

- src/controllers/CanvasController.ts
- src/controllers/SubscriberController.ts
- src/index.ts
- src/interactions/connector.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/__mocks__/config.ts
- src/tests/controllers/CanvasController.test.ts
- src/tests/controllers/SubscriberContoller.test.ts
- src/tests/interactions/connector.test.tsx
- types/CommonTypes.ts
This PR adds getter and setter for the scale factor of the canvas
-   [EDT-759](https://support.chili-publish.com/browse/EDT-759)
> [EDT-759] get/set zoomPercentage

- src/README.md
- src/README_HTML.md
- src/controllers/FontController.ts
This PR adds  missing controllers to the SDK documentation
> [Fix] Add missing controllers to the SDK documentation

- src/README.md
- src/README_HTML.md
- src/controllers/ActionController.ts
- src/controllers/SubscriberController.ts
- src/index.ts
- src/interactions/connector.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/__mocks__/config.ts
- src/tests/controllers/ActionController.test.ts
- src/tests/controllers/SubscriberContoller.test.ts
- src/tests/interactions/connector.test.tsx
- tsconfig.json
- types/ActionTypes.ts
- types/CommonTypes.ts
- types/DocumentTypes.ts
This PR adds `actions`-related methods to the SDK. 
- onActionsChanged
- createAction
- removeAction
- updateActionTriggers
- updateActionScript
-   [EDT-715](https://support.chili-publish.com/browse/EDT-715)
> [Feature] Add `Actions` SDK methods

- src/controllers/TextStyleController.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/TextStyleController.test.ts
> [EDT 764] - add function to clear local text formatting

- src/index.ts
- types/FrameTypes.ts
This PR adds a missing `isConstrained` property and adds shape frame type.
> [Fix] Add missing isConstrained & Shape model

- src/controllers/ToolController.ts
- src/tests/controllers/ToolController.test.ts
- src/utils/enums.ts
This PR adds methods to set shape tool
-   [EDT-798](https://support.chili-publish.com/browse/EDT-798)
> [Feature] Add set shape tool methods

- src/controllers/FrameController.ts
- src/tests/__mocks__/MockEditorAPI.ts
- src/tests/controllers/FrameController.test.ts
- types/FrameTypes.ts
This PR rename constraint property and SDK naming, WRS should be updated.
> [Fix] Constraints renaming

- types/FrameTypes.ts
This PR Adds missing attributes to the ShapeFrame type
-   [WRS-963](https://support.chili-publish.com/projects/WRS/issues/WRS-963)
> Add missing attributes to the ShapeFrame type

- README.md
> [Fix] Cleanup README

- src/controllers/SubscriberController.ts
- src/index.ts
- src/interactions/connector.ts
- src/tests/__mocks__/config.ts
- src/tests/controllers/SubscriberContoller.test.ts
- src/types/ActionTypes.ts
- src/types/CommonTypes.ts
- types/Actions.d.ts
This PR aligns the action triggers with the engine. 
-   [EDT-722](https://support.chili-publish.com/browse/EDT-722)
> [Feature] Update Action Triggers

- src/interactions/connector.ts
This PR uses the correct connector for crop enter mode
> [Fix] use correct connector

- src/types/ActionTypes.ts
This PR makest he actions trigger typing more strict to reduce the chance of mistakes
> [Fix] Actions Trigger Typing more strict

- types/Actions.d.ts
This PR fixes an issue with the layout typing in actions type declarations
> [Fix] Layout action typing issue

- src/controllers/VariableController.ts
[EDT-989](https://support.chili-publish.com/browse/EDT-989)
Can be tested against https://studio.chiligrafx-dev.com/?workspace=latest&engine=239
> [Fix] Add setImageVariableConnector

- package.json
- src/index.ts
- src/interactions/connector.ts
- src/tests/interactions/connector.test.tsx
- src/types/CommonTypes.ts
- src/types/ConfigurationTypes.ts
This PR adds a new `StudioStyling` property to the `Config` to be able to set the Studio background color in the engine
-   [EDT-968](https://support.chili-publish.com/browse/EDT-968)
[EDT-968]: https://chilipublishintranet.atlassian.net/browse/EDT-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDT-968] StudioStyling added

- src/controllers/FrameController.ts
- src/tests/controllers/FrameController.test.ts
This PR restores the setImageFromConnector call to previous version
> [Fix] Restore breaking change in setImageFromConnector

- src/utils/enums.ts
Experimental feature to add pdf as a downloadtype
> [Feature] Add pdf as downloadtype

- src/controllers/VariableController.ts
- src/index.ts
- src/tests/controllers/VariableController.test.ts
- src/types/VariableTypes.ts
- types/Actions.d.ts
This PR adds the new boolean variable type.
Can be tested against https://studio.chiligrafx-dev.com/bench.html?workspace=latest&engine=293
EDT-983
WRS-1201
WRS-1202
> [Feature] Add boolean variable type

- src/types/VariableTypes.ts
> [Feature] add missing enum entry

- yarn.lock
> [Fix] update dependencies reported by dependabot

- package.json
This PR Fixes the version after accidental version bump
> [Fix] tag numbers and SDK version

- src/controllers/ColorConversionController.ts
- src/sdk.ts
- src/tests/controllers/ColorConversionController.test.ts
- src/types/ColorStyleTypes.ts
This PR adds support for converting colors to display RGB colors
- Supported colors list has been updated with actually supported colors.
- Color object is now a union type of all supported types
> [FEATURE][EDT-1096] Add color conversion support

- types/Actions.d.ts
This PR adds a missing method to actions: `studio.layouts.byName`
-   [EDT-1090](https://chilipublishintranet.atlassian.net/browse/EDT-1090)
[EDT-1090]: https://chilipublishintranet.atlassian.net/browse/EDT-1090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][EDT-1090] Actions -> studio.layouts.byName

- src/controllers/SubscriberController.ts
- src/interactions/connector.ts
- src/tests/controllers/SubscriberContoller.test.ts
Fix bad linking to the engine.
> [Fix] Async error communication system (adjustments)

- package.json
This PR loossens the node dependency rules for newer Node versions
-   #338
> [Fix] Loosen node rules for newer versions

- src/controllers/InfoController.ts
- src/sdk.ts
- src/tests/controllers/InfoController.test.ts
This PR adds the InfoController to get properties like SDK version and Engine version
-   [WRS-1328](https://support.chili-publish.com/projects/WRS/issues/WRS-1328)
[WRS-1328]: https://chilipublishintranet.atlassian.net/browse/WRS-1328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature] Add InfoController

- .github/workflows/publish-package.yml
- .github/workflows/publish-release-npm.yml
Removing the work directory override
> [EDT-1155] Fix main branch build workflows v2

- packages/sdk/src/types/FontTypes.ts
This PR adds `fontStyles` array to `DocumentFontFamily`
> [FIX] [NO-TICKET] font styles added to family

- packages/actions/training.json
> [NO-TICKET] [Genie] Processed testing feedback

- .github/pull_request_comment_template.md
- .github/workflows/pr-build.yml
- .github/workflows/pr-comment-on-open.yml
This PR is cherry picked from the not-soon-to-merge PR https://github.com/chili-publish/studio-sdk/pull/362
> [NO-TICKET] Add private builds of SDK 

- packages/sdk/src/controllers/ConnectorController.ts
- packages/sdk/src/tests/controllers/ConnectorController.test.ts
This PR
-   [EDT-1167](https://chilipublishintranet.atlassian.net/browse/EDT-1167) in scope of this ticket only the method comments and test values were changed
[EDT-1167]: https://chilipublishintranet.atlassian.net/browse/EDT-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDT-1167] - connector mapping to variable ids

- packages/sdk/package.json
This PR adds the README to the NPM release
> [Fix] Add README to SDK NPM release

- packages/sdk/src/controllers/SubscriberController.ts
- packages/sdk/src/interactions/connector.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/tests/controllers/SubscriberContoller.test.ts
- packages/sdk/src/types/CommonTypes.ts
> [Fix] Add active layout unit stream

- packages/sdk/src/controllers/SubscriberController.ts
- packages/sdk/src/interactions/connector.ts
- packages/sdk/src/tests/controllers/SubscriberContoller.test.ts
- packages/sdk/src/types/CommonTypes.ts
- packages/sdk/src/types/ConnectorTypes.ts
There are 3 different 401 case:
- grafx token needs to be renewed
- 3rd party auth needs to be renewed (user impersonation)
- issue w/ auth on 3rd party (different from renewal)
- https://chilipublishintranet.atlassian.net/browse/EDT-1258
- https://chilipublishintranet.atlassian.net/browse/WRS-1487
> [Feature] Support for 3rd party auth

- .github/workflows/publish-release-npm.yml
This PR tries to fix the issue on npm release that causes a misallignment between NPM version and package version
> [Fix] Change tag on npm release

- .github/workflows/pr-merge.yml
- .github/workflows/publish-release-npm.yml
This PR fixes the release issues and a trial for the version mismatch issue
> [Fix] SDK publish fail on connector and version mismatch

- packages/sdk/src/controllers/LayoutController.ts
- packages/sdk/src/index.ts
- packages/sdk/src/tests/controllers/LayoutController.test.ts
- packages/sdk/src/types/DocumentTypes.ts
- packages/sdk/src/types/LayoutTypes.ts
This PR
-   [EDT-1302](https://chilipublishintranet.atlassian.net/browse/EDT-1302)
-   [WRS-1560](https://chilipublishintranet.atlassian.net/browse/WRS-1560)
[EDT-1302]: https://chilipublishintranet.atlassian.net/browse/EDT-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WRS-1560]: https://chilipublishintranet.atlassian.net/browse/WRS-1560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FEATURE][EDT-1302] Add layout intent to SDK

- packages/sdk/src/controllers/SubscriberController.ts
- packages/sdk/src/interactions/connector.ts
- packages/sdk/src/tests/controllers/SubscriberContoller.test.ts
- packages/sdk/src/types/CommonTypes.ts
- packages/sdk/src/types/ConnectorTypes.ts
This PR updates the `onAuthExpired` stream.
-   [EDT-1296](https://chilipublishintranet.atlassian.net/browse/EDT-1296)
-   [WRS-1541](https://chilipublishintranet.atlassian.net/browse/WRS-1541)
-   [WRS-1465](https://chilipublishintranet.atlassian.net/browse/WRS-1465)
[EDT-1296]: https://chilipublishintranet.atlassian.net/browse/EDT-1296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WRS-1541]: https://chilipublishintranet.atlassian.net/browse/WRS-1541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WRS-1465]: https://chilipublishintranet.atlassian.net/browse/WRS-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Fix] Change onAuthExpired

- packages/sdk/tsconfig.json
This PR adds all necessary files to the documentation by using wildcards
> [Fix] [No-Ticket] Wildcard SDK documentation

- packages/sdk/src/controllers/SubscriberController.ts
- packages/sdk/src/interactions/connector.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/tests/__mocks__/config.ts
- packages/sdk/src/tests/controllers/SubscriberContoller.test.ts
- packages/sdk/src/types/CommonTypes.ts
- packages/sdk/src/types/TextStyleTypes.ts
This PR
https://chilipublishintranet.atlassian.net/browse/EDT-1349
unlocks:
https://chilipublishintranet.atlassian.net/browse/WRS-1552
https://chilipublishintranet.atlassian.net/browse/WRS-1551
---
Also added `BASELINE_SHIFT = 'baselineShiftValue'` to `SelectedTextStyles` enum.
> [Fix] Add onViewModeChanged

- packages/sdk/src/controllers/SubscriberController.ts
- packages/sdk/src/index.ts
- packages/sdk/src/interactions/connector.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/tests/__mocks__/config.ts
- packages/sdk/src/tests/controllers/SubscriberContoller.test.ts
- packages/sdk/src/types/CommonTypes.ts
- packages/sdk/src/types/ViewportTypes.ts
This PR
https://chilipublishintranet.atlassian.net/browse/EDT-322
Also fixes the connector issue https://chilipublishintranet.atlassian.net/browse/EDT-1421
---
Please share your thoughts on naming.
> [Feature] Add onViewportRequested

- packages/sdk/src/controllers/SubscriberController.ts
- packages/sdk/src/interactions/connector.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/tests/controllers/SubscriberContoller.test.ts
- packages/sdk/src/types/CommonTypes.ts
This PR adds a new subscription to be able to react to connector list changes
-   [EDT-1253](https://chilipublishintranet.atlassian.net/browse/EDT-1253)
[EDT-1253]: https://chilipublishintranet.atlassian.net/browse/EDT-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][EDT-1253] onConnectorsChanged subscription

- packages/sdk/src/index.ts
This PR
-   [WRS-1613](https://support.chili-publish.com/projects/WRS/issues/WRS-1613)
[WRS-1613]: https://chilipublishintranet.atlassian.net/browse/WRS-1613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Fix][WRS-1613] re export connector types to index.ts

- packages/sdk/src/controllers/BarcodeController.ts
- packages/sdk/src/controllers/FrameController.ts
- packages/sdk/src/sdk.ts
> Mark barcodes as experimental for now

- package.json
- packages/sdk/editor-engine.json
This PR bumps the engine to 1.6.latest so adds support for engine hotfixes.
> [Feature] Bump Engine to 1.6.latest

- packages/sdk/src/controllers/BarcodeController.ts
- packages/sdk/src/tests/controllers/BarcodeController.test.ts
- packages/sdk/src/types/BarcodeTypes.ts
- packages/sdk/src/types/FrameTypes.ts
This PR
-   [EDT-1472](https://chilipublishintranet.atlassian.net/browse/EDT-1472)
[EDT-1472]: https://chilipublishintranet.atlassian.net/browse/EDT-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FEATURE] [EDT-1472] Allow controlling surrounding characters

- packages/sdk/src/README.md
- packages/sdk/src/controllers/BarcodeController.ts
- packages/sdk/src/controllers/VariableController.ts
- packages/sdk/src/tests/controllers/VariableController.test.ts
- packages/sdk/src/types/VariableTypes.ts
This PR
-   [EDT-1476](https://chilipublishintranet.atlassian.net/browse/EDT-1476)
[EDT-1476]: https://chilipublishintranet.atlassian.net/browse/EDT-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature] [EDT-1476] Add methods related to number variables

- packages/connectors/src/MediaConnector.ts
This PR
-   [WRS-1753](https://support.chili-publish.com/projects/WRS/issues/WRS-1753)
[WRS-1753]: https://chilipublishintranet.atlassian.net/browse/WRS-1753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][WRS-1753] Extend "MediaConnectorCapabilities" with new "metadata" field

- .editorconfig
- .github/workflows/publish-release-npm.yml
- package.json
- packages/sdk/editor-engine.json
> [Feature] Bump Engine to 1.7.latest

- packages/sdk/src/types/ConnectorTypes.ts
> [Fix] Add missed "metadata" capability for SDK types

- packages/connectors/src/Connector.Shared.ts
This PR adds `ConnectorHttpError` to `@chili-publish/studio-connectors` package.
-   [EDT-1486](https://chilipublishintranet.atlassian.net/browse/EDT-1486)
[EDT-1486]: https://chilipublishintranet.atlassian.net/browse/EDT-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature] Add `ConnectorHttpError`

- packages/sdk/src/README.md
- packages/sdk/src/next/index.ts
- packages/sdk/src/next/types/NextSubscribers.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/types/CommonTypes.ts
This PR
In context of this ticket we introduce possibility to listen event streams from `next` version
-   [WRS-1760](https://support.chili-publish.com/projects/WRS/issues/WRS-1760)
[WRS-1760]: https://chilipublishintranet.atlassian.net/browse/WRS-1760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feat][WRS-1760] Introduce enabling of next subscribers

- package.json
- packages/sdk/editor-engine.json
> [Feature] Bump Engine to 1.8.latest

- packages/actions/.prettierrc.js
- packages/actions/package.json
- packages/actions/src/ActionHelpers.ts
- packages/actions/types/Actions.d.ts
- packages/actions/yarn.lock
This PR expose date variables in actions
https://chilipublishintranet.atlassian.net/browse/EDT-1509
https://chilipublishintranet.atlassian.net/browse/PRODUCT-537
https://chilipublishintranet.atlassian.net/browse/PRODUCT-542
> [EDT-1509] Expose date variables in actions

- packages/actions/src/ActionHelpers.ts
- packages/actions/types/Actions.d.ts
- packages/sdk/src/controllers/VariableController.ts
This PR adds code comments about dates for Genie.
(Also updated SDK-side for actual humans)
https://chilipublishintranet.atlassian.net/browse/EDT-1559
https://chilipublishintranet.atlassian.net/browse/PRODUCT-537
> [Fix] [EDT-1559] Code comments for Genie

- packages/actions/src/ActionHelpers.ts
- packages/actions/types/Actions.d.ts
- packages/sdk/src/controllers/VariableController.ts
This PR fixes a wrong mention on localizable date pattern.
https://chilipublishintranet.atlassian.net/browse/EDT-1559
https://chilipublishintranet.atlassian.net/browse/PRODUCT-537
Closes #484
> [Fix] Localized date pattern

- package.json
- packages/sdk/editor-engine.json
This PRbumps the engine to 1.9.latest
> [Feature] Bump Engine to 1.9.latest

- packages/sdk/src/controllers/FrameController.ts
- packages/sdk/src/index.ts
- packages/sdk/src/tests/controllers/FrameController.test.ts
- packages/sdk/src/types/FrameTypes.ts
This PR
-   [EDT-1534](https://chilipublishintranet.atlassian.net/browse/EDT-1534)
[EDT-1534]: https://chilipublishintranet.atlassian.net/browse/EDT-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FEATURE][EDT-1534] Add SDK methods for auto-grow

- .github/workflows/pr-merge.yml
> [Fix] Add auth for bump

- .github/workflows/pr-merge.yml
This PR adds the gh token for version bump
> [Fix] Add gh token

- .github/workflows/pr-merge.yml
This PR reverts back to gh action, but with prerelease
> [fix] Prerelease with phips28/gh-action-bump-version

- .github/workflows/publish-release-npm.yml
This PR fixes the PR release flow bump
> [Fix] Switch prerelease to patch on release

- packages/sdk/src/controllers/VariableController.ts
- packages/sdk/src/tests/controllers/VariableController.test.ts
- packages/sdk/src/types/VariableTypes.ts
This PR
-   [EDT-1589](https://chilipublishintranet.atlassian.net/browse/EDT-1589)
[EDT-1589]: https://chilipublishintranet.atlassian.net/browse/EDT-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][EDT-1589] set/resetHelpText methods

- package.json
- packages/sdk/editor-engine.json
This PR bumps the engine to 1.10.latest
> [Feature] Bump Engine to 1.10.latest

- .github/workflows/publish-release-npm.yml
This PR skips the push on version bump
> [Fix] Skip push on bump

- packages/sdk/src/controllers/FrameController.ts
- packages/sdk/src/tests/controllers/FrameController.test.ts
- packages/sdk/src/types/FrameTypes.ts
This PR corrects the auto grow reset models so they are the same as on engine side.
> [Fix] Correct auto grow reset models

- .github/workflows/publish-release-npm.yml
This PR aligns the releaseflow with our other repositories
> [Fix] Align releaseflow with other repo's

- packages/sdk/editor-engine.json
This PR releases (w/ engine 1.11)
> [Feature] Bump Engine to 1.11.latest

- packages/sdk/src/controllers/VariableController.ts
- packages/sdk/src/index.ts
- packages/sdk/src/next/tests/controllers/VariableController.test.ts
- packages/sdk/src/tests/controllers/VariableController.test.ts
- packages/sdk/src/types/VariableTypes.ts
This PR
https://chilipublishintranet.atlassian.net/browse/EDT-1608
> [Feature] Add private data

- packages/sdk/src/controllers/ColorStyleController.ts
- packages/sdk/src/tests/controllers/ColorStyleController.test.ts
- packages/sdk/src/types/ColorStyleTypes.ts
This PR
-   [EDT-1617](https://chilipublishintranet.atlassian.net/browse/EDT-1617)
[EDT-1617]: https://chilipublishintranet.atlassian.net/browse/EDT-1617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FEATURE][EDT-1617] Add spot colors

- packages/actions/src/ActionHelpers.ts
- packages/actions/training.json
- packages/actions/types/Actions.d.ts
- packages/sdk/src/controllers/VariableController.ts
This PR teaches genie that line breaks are not allowed on short text variable values.
https://chilipublishintranet.atlassian.net/browse/EDT-1633
> [Fix] Teach genie about line breaks

- packages/sdk/editor-engine.json
> [Feature] Bump engine version to 1.12.x

- package.json
- packages/actions/package.json
- packages/connectors/package.json
- packages/sdk/package.json
> [Fix] Set SDK version to 1.16.0-rc.0

- bundle-size.json
This PR
-   [GRAFX-3560](https://support.chili-publish.com/projects/WRS/issues/GRAFX-3560)
[GRAFX-3560]: https://chilipublishintranet.atlassian.net/browse/GRAFX-3560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Fix] [GRAFX-3560] Add bundle size

- packages/connectors/src/index.ts
This PR re-export Data Connector Contract in index
> [Fix] Re-export Data connector in index

- packages/connectors/src/DataConnector.ts
- packages/sdk/src/types/DataConnectorTypes.ts
This PR makes filters and soring nillable
> [NO-TICKET] nullable filters and sorting in PageConfig

- packages/sdk/src/controllers/PageController.ts
- packages/sdk/src/tests/controllers/PageController.test.ts
This PR allow page reordering.
https://chilipublishintranet.atlassian.net/browse/EDT-1699
https://github.com/chili-publish/studio-engine/pull/1535
> [Feature] Allow page reordering

- packages/sdk/editor-engine.json
This PR prepares everything for the big 1.17 release
> [Release] prep for 1.17

- packages/sdk/src/controllers/FrameController.ts
- packages/sdk/src/tests/controllers/FrameController.test.ts
- packages/sdk/src/types/FrameTypes.ts
This PR
-   [EDT-1694](https://chilipublishintranet.atlassian.net/browse/EDT-1694)
[EDT-1694]: https://chilipublishintranet.atlassian.net/browse/EDT-1694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][EDT-1694] Deprecate resetAutoGrow related methods and types

- packages/sdk/src/controllers/VariableController.ts
- packages/sdk/src/types/VariableTypes.ts
This PR
-   [EDT-1710](https://chilipublishintranet.atlassian.net/browse/EDT-1710)
[EDT-1710]: https://chilipublishintranet.atlassian.net/browse/EDT-1710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][EDT-1710] Make labels nullable

- .github/workflows/publish-release-npm.yml
- packages/actions/package.json
- packages/connectors/package.json
- packages/sdk/editor-engine.json
- packages/sdk/package.json
> [Release] prep for 1.18

- packages/sdk/src/controllers/SubscriberController.ts
- packages/sdk/src/controllers/UndoManagerController.ts
- packages/sdk/src/tests/__mocks__/config.ts
- packages/sdk/src/tests/controllers/SubscriberContoller.test.ts
- packages/sdk/src/tests/controllers/UndoManagerController.test.ts
- packages/sdk/src/types/CommonTypes.ts
This PR
-   [EDT-1745](https://chilipublishintranet.atlassian.net/browse/EDT-1745)
[EDT-1745]: https://chilipublishintranet.atlassian.net/browse/EDT-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][EDT-1745] Custom undo state

- examples/sdk/aqa-typescript-auth-example/index.html
- examples/sdk/aqa-typescript-auth-example/src/app.ts
This PR
-   [WRS-2184](https://support.chili-publish.com/projects/WRS/issues/WRS-2184)
[WRS-2184]: https://chilipublishintranet.atlassian.net/browse/WRS-2184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Task][WRS-2184] Cached login credentials and automatic redirect to login if not authenticated

- packages/sdk/src/controllers/LayoutController.ts
- packages/sdk/src/controllers/VariableController.ts
- packages/sdk/src/index.ts
- packages/sdk/src/tests/controllers/LayoutController.test.ts
- packages/sdk/src/tests/controllers/VariableController.test.ts
- packages/sdk/src/types/CommonTypes.ts
- packages/sdk/src/types/VariableTypes.ts
This PR
-   [EDT-1755](https://chilipublishintranet.atlassian.net/browse/EDT-1755)
[EDT-1755]: https://chilipublishintranet.atlassian.net/browse/EDT-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][EDT-1755] Add private data to layout

- packages/sdk/src/types/FrameTypes.ts
> [FIX] Add smartCrop and manualCrop fitModes

- packages/sdk/src/controllers/LayoutController.ts
- packages/sdk/src/tests/controllers/LayoutController.test.ts
- packages/sdk/src/types/LayoutTypes.ts
This PR adds layout user selection.
https://chilipublishintranet.atlassian.net/browse/EDT-1813
> [Feature] Add setSelectedByUser

- packages/sdk/src/controllers/VariableController.ts
- packages/sdk/src/tests/controllers/VariableController.test.ts
This PR
-   [EDT-1801](https://chilipublishintranet.atlassian.net/browse/EDT-1801)
[EDT-1801]: https://chilipublishintranet.atlassian.net/browse/EDT-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][EDT-1801] Fix wrong api method/SDK contract

- packages/sdk/src/controllers/VariableController.ts
- packages/sdk/src/next/tests/controllers/VariableController.test.ts
- packages/sdk/src/tests/controllers/VariableController.test.ts
- packages/sdk/src/types/VariableTypes.ts
This PR
-   [EDT-1801](https://chilipublishintranet.atlassian.net/browse/EDT-1801)
[EDT-1801]: https://chilipublishintranet.atlassian.net/browse/EDT-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Fix][EDT-1801] Fix wrongly removed property

- packages/sdk/src/controllers/LayoutController.ts
- packages/sdk/src/index.ts
- packages/sdk/src/tests/controllers/CharacterStyleController.test.ts
- packages/sdk/src/tests/controllers/LayoutController.test.ts
- packages/sdk/src/types/LayoutTypes.ts
This PR adds the `setResizableByUser` layout method.
https://chilipublishintranet.atlassian.net/browse/EDT-1823
---
Engine PR: https://github.com/chili-publish/studio-engine/pull/1663
> [Feature] Add resizableByUser

- .github/workflows/publish-release-npm.yml
- .github/workflows/update-engine-version.yml
This PR automates the version management update + adds a new workflow for updating the version of the engine manually in case of a hotfix.
> [Fix] Automate version management and add workflow for manual update

- package.json
- packages/actions/package.json
- packages/connectors/package.json
- packages/sdk/editor-engine.json
- packages/sdk/package.json
- packages/sdk/src/tests/controllers/VariableController.test.ts
- packages/sdk/src/types/PageTypes.ts
This PR prepares versions of 1.20 release
> [Release] Prep for 1.20

- .github/workflows/publish-docs.yml
This PR fixes the publishing of the docs
> [Fix] Docs fix publish

- packages/actions/src/ActionHelpers.ts
- packages/actions/types/Actions.d.ts
- types/Actions.d.ts
This PR adds the keepPageSize parameter in actions
https://chilipublishintranet.atlassian.net/browse/EDT-1826
> [Fix] Add keepPageSize parameter

- packages/sdk/src/types/LayoutTypes.ts
> [Fix][EDT-1878] Add original layout size to layout model

- packages/sdk/package.json
- packages/sdk/yarn.lock
This PR fixes the typedoc generation
> [Fix] Typedoc doc generation

- packages/sdk/src/types/PageTypes.ts
This PR will make page sizes always resolved (not nullable anymore).
https://chilipublishintranet.atlassian.net/browse/EDT-1855
> [Breaking] Page size is always resolved

- package.json
- packages/actions/package.json
- packages/connectors/package.json
- packages/sdk/editor-engine.json
- packages/sdk/package.json
> [Release] Prep for 1.22

- .github/workflows/publish-release-npm.yml
This PR fixes the RC build stripping on prd
> [Fix] Release management fix stripping rc version

- .github/workflows/publish-release-uat.yml
- .github/workflows/update-engine-version.yml
This PR adds the UAT deploy step, for version management only
> [Fix] Add UAT deploy (version-management only)

- packages/sdk/src/controllers/ColorConversionController.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/tests/controllers/ColorConversionController.test.ts
> [Fix] `convertToRgb` not working

- package.json
- packages/actions/package.json
- packages/connectors/package.json
- packages/sdk/editor-engine.json
- packages/sdk/package.json
> [Release] Prep for 1.23.0

- packages/sdk/src/controllers/PageController.ts
- packages/sdk/src/next/controllers/PageController.ts
- packages/sdk/src/next/tests/controllers/PageController.test.ts
- packages/sdk/src/tests/controllers/PageController.test.ts
This PR
-   [EDT-1963](https://support.chili-publish.com/projects/EDT/issues/EDT-1963)
[EDT-1963]: https://chilipublishintranet.atlassian.net/browse/EDT-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Hotfix release] 1.23.1 [EDT-1963] Add set page size method

- packages/sdk/src/controllers/FrameController.ts
- packages/sdk/src/index.ts
- packages/sdk/src/tests/controllers/FrameController.test.ts
- packages/sdk/src/types/EngineEditModeTypes.ts
- packages/sdk/src/types/FrameTypes.ts
This PR requires the corresponding engine PR
-   [EDT-1930](https://chilipublishintranet.atlassian.net/browse/EDT-1930)
[EDT-1930]: https://chilipublishintranet.atlassian.net/browse/EDT-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDT-1930] Add methods/types for per asset crop

- .github/workflows/publish-release-uat.yml
- package.json
- packages/actions/package.json
- packages/connectors/package.json
- packages/sdk/package.json
- packages/sdk/src/sdk.ts
- packages/sdk/src/types/global.d.ts
- packages/sdk/webpack.config.js
This PR fixes the UAT build with another engine domain
> [Fix] uat build

- .github/workflows/publish-release-npm.yml
- .github/workflows/publish-release-uat.yml
> [Fix] Use bump version incrementation for UAT release

- packages/sdk/editor-engine.json
> [Fix] Update engine version for UAT release

- package.json
- packages/actions/package.json
- packages/connectors/package.json
- packages/sdk/package.json
> [Fix] new patch release

- packages/sdk/src/tests/controllers/CharacterStyleController.test.ts
- packages/sdk/src/tests/controllers/ParagraphStyleController.test.ts
- packages/sdk/src/types/CharacterStyleTypes.ts
- packages/sdk/src/types/ParagraphStyleTypes.ts
- packages/sdk/src/types/TextStyleTypes.ts
This PR also updates the models to include some missing properties
-   [EDT-1888](https://chilipublishintranet.atlassian.net/browse/EDT-1888)
[EDT-1888]: https://chilipublishintranet.atlassian.net/browse/EDT-1888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature][EDT-1888] Update text models to include text stroke

- yarn.lock
This PR fixes dependabot alerts
> [Fix] Dependabot alerts

- packages/sdk/src/controllers/BrandKitController.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/tests/controllers/BrandKitController.test.ts
This PR adds brandkit id & version management.
https://chilipublishintranet.atlassian.net/browse/EDT-1918
> [Fix] Add brandKit versioning

- packages/sdk/src/interactions/Connector.ts
> [EDT-1610] Point to new file

- .github/workflows/release-pr.yml
This PR
-   [WRS-2501](https://support.chili-publish.com/projects/WRS/issues/WRS-2501)
[WRS-2501]: https://chilipublishintranet.atlassian.net/browse/WRS-2501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feature] [WRS-2501] Add workflow to create/update release PR

- packages/sdk/src/controllers/BrandKitController.ts
- packages/sdk/src/controllers/UndoManagerController.ts
- packages/sdk/src/tests/controllers/UndoManagerController.test.ts
This PR removes the need for try/catch and handle the undo rollback automatically.
The underlying behavior has been changed from the engine-side.
https://chilipublishintranet.atlassian.net/browse/EDT-2029
> [Fix] Make undo.record safer and simpler to use

- package.json
- packages/actions/package.json
- packages/connector-types/package.json
- packages/connectors/package.json
- packages/sdk/editor-engine.json
- packages/sdk/package.json
> Prepare for UAT 1.27.0-rc.0

- package.json
- packages/actions/package.json
- packages/connector-types/package.json
- packages/connectors/package.json
- packages/sdk/editor-engine.json
- packages/sdk/package.json
> Prepare for UAT 1.28.0

- package.json
- packages/actions/package.json
- packages/connector-types/package.json
- packages/connectors/package.json
- packages/sdk/editor-engine.json
- packages/sdk/package.json
> Prepare for release 1.30

- .github/workflows/publish-release-uat.yml
> [Fix] restore UAT release process

- packages/sdk/src/controllers/FontController.ts
- packages/sdk/src/index.ts
- packages/sdk/src/tests/controllers/FontController.test.ts
- packages/sdk/src/types/FontTypes.ts
- packages/sdk/src/types/ParagraphStyleTypes.ts
- packages/sdk/src/types/TextStyleTypes.ts
> [EDT-2027] - Add support for bulleted lists in text flow model

- packages/sdk/src/types/DocumentTypes.ts
This PR
-   [EDT-2124](https://chilipublishintranet.atlassian.net/browse/EDT-2124)
[EDT-2124]: https://chilipublishintranet.atlassian.net/browse/EDT-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🏷️ [Feature][EDT-2124] Component target

- package.json
- packages/actions/package.json
- packages/connector-types/package.json
- packages/connectors/package.json
- packages/sdk/package.json
> [Fix] Bump version

- .github/workflows/publish-release-npm.yml
- .github/workflows/publish-release-uat.yml
This PR
-   [GRAFX-5066](https://support.chili-publish.com/projects/WRS/issues/GRAFX-5066)
[GRAFX-5066]: https://chilipublishintranet.atlassian.net/browse/GRAFX-5066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Fix][GRAFX-5066] Use Github app token for release workflows
